### ISSUE TITLE
Update wiki links

### ISSUE THREAD

**Issue by al3xxx** [ohmybash/oh-my-bash#1]
Hello,
All oh-my-bash wiki links go to nowhere.

**Comment by nntoan** [comment]
Hi @al3xxx,

The wiki document is such a big big thing for me. Feel free to help me contribute it :)

**Comment by simoneduca** [comment]
Did you make any progress on this? It looks like the wiki links are still going nowhere.

**Comment by dahveed311** [comment]
This is still broken. I can't view any themes or plugins, which is providing motivation to just abandon oh-my-bash entirely.

**Comment by simoneduca** [comment]
Unfortunately, that's what I ended up doing. Mostly because I don't have time atm to contribute to the docs.

**Comment by Amolith** [comment]
I'm about to abandon it as well and go to zsh  and oh-my-zsh. Zsh is compatible with bash, which is nice.

**Comment by che666** [comment]
Fix this please... can not be that hard to set proper access permissions for the wiki.

**Comment by newtorob** [comment]
Yup, still not working, kind of hard to set themes or plugins without working links

**Comment by nntoan** [comment]
I've just fixed the permission issue on Wiki pages, without #10 I even don't know permissions denied :)

**Comment by JSn1nj4** [comment]
@nntoan does this also mean the screenshots themselves don't exist yet?

**Comment by maikeldotuk** [comment]
This wiki should be renamed to "there's no actual wiki". An index page linking to nowhere useful cannot be called a wiki. At least put an "under construction" sign or something indicating you don't have the time to do the wiki. 
I've spent half an hour thinking I was missing some link, or my Chromium addons were breaking the wiki because you explicitely say "check all the themes in the wiki" as if such page existed.

**Comment by newtorob** [comment]
Right I agree @maikeldotuk it is very confusing to try and set up when there's no official documentation.

**Comment by Kreyren** [comment]
Referencing https://github.com/ohmybash/oh-my-bash/wiki issue still present

**Comment by Kreyren** [comment]
@nntoan recommends pinning this issue

**Comment by DanteAlighierin** [comment]
Having not found articles on the Internet about your project, I decided to write an article on my site. I think this article will benefit your project.

**Comment by nntoan** [comment]
Thank to everyone! I'm closing this ticket as we actually have Wiki now. 🍻
