### ISSUE TITLE
why so many blank in my terminal

### ISSUE THREAD

**Issue by dongxi8** [ohmybash/oh-my-bash#314]
![image](https://user-images.githubusercontent.com/1157840/155960277-006eee86-e09a-4712-8a32-9b08bc792e25.png)

os： 
![image](https://user-images.githubusercontent.com/1157840/155960370-0785d85c-a319-4433-8630-e18fd846d620.png)

**Comment by akinomyoga** [comment]
Thanks for the report.

- **Q1**: What is your terminal?
- **Q2**: Could you copy and paste the result of <kbd>Ctrl+x</kbd><kbd>Ctrl+v</kbd>?

**Comment by akinomyoga** [comment]
> akinomyoga/ble.sh#181

Ah, OK. Thank you. I haven't missed it. Anyway, I'd like to check how the terminal is detected. Could you paste the result of the following command?

> * **Q2**: Could you copy and paste the result of Ctrl+xCtrl+v?

**Comment by dongxi8** [comment]
![image](https://user-images.githubusercontent.com/1157840/155965901-b37fc404-fe5f-4495-86f6-7f78743cb1ab.png)

**Comment by dongxi8** [comment]
nothing happened if I type  Ctrl+x

**Comment by akinomyoga** [comment]
Could you type <kbd>Ctrl+x</kbd><kbd>Ctrl+v</kbd> in a row?

**Comment by dongxi8** [comment]
> Could you type Ctrl+xCtrl+v in a row? This is a double-key keybinding.

GNU bash, version 4.3.48(1)-release (x86_64-pc-linux-gnu) with ble.sh

**Comment by akinomyoga** [comment]
Ah, OK! So you are using ble-0.3! This is actually fixed in ble-0.4. Could you use the latest version of ble.sh?

**Comment by dongxi8** [comment]
> Ah, OK! So you are using ble-0.3! This is actually fixed in ble-0.4. Could you use the latest version of ble.sh?

it increase the blank

![image](https://user-images.githubusercontent.com/1157840/155966830-d4d5bfa8-7dc0-4b3e-80f8-e57787bdcaf8.png)

**Comment by akinomyoga** [comment]
Hmm, OK. Thanks. What would be shown with <kbd>Ctrl-x</kbd><kbd>Ctrl-v</kbd> this time?

**Comment by dongxi8** [comment]
> Hmm, OK. Thanks. What would be shown with Ctrl-xCtrl-v this time?
> 
> **Edit**:
> 
> > I use this version, https://github.com/akinomyoga/ble.sh/releases/download/v0.4.0-devel2/ble-0.4.0-devel2.tar.xz
> 
> Ah, OK. This might be still old. Could you try the `master` branch?
> 
> **Edit**:
> 
> If you don't have `git`, `gawk` or `make`, please download this one: [ble-0.4.0-devel3+b9fdaab.zip](https://github.com/ohmybash/oh-my-bash/files/8152555/ble-0.4.0-devel3%2Bb9fdaab.zip).

still have this issue


`GNU bash, version 4.3.48(1)-release (x86_64-pc-linux-gnu)
ble.sh, version 0.4.0-devel3+b9fdaab (noarch)
oh-my-bash (powerline), version 1.0.0+209ffda0 (noarch), aliases(general), completions(git composer ssh), plugins(git bashmarks)
locale: LANG=en_US.UTF-8 LC_ADDRESS=zh_CN.UTF-8 LC_COLLATE=C LC_CTYPE=en_US.UTF-8 LC_IDENTIFICATION=zh_CN.UTF-8 LC_MEASUREMENT=zh_CN.UTF-8 LC_MONETARY=zh_CN.UTF-8 LC_NAME=zh_CN.UTF-8 LC_NUMERIC=zh_CN.UTF-8 LC_PAPER=zh_CN.UTF-8 LC_TELEPHONE=zh_CN.UTF-8 LC_TIME=zh_CN.UTF-8
terminal: TERM=xterm wcwidth=8.0-west/14.0-2+ri, vte:2802 (1;2802;0)
`

**Comment by akinomyoga** [comment]
Hmm, OK!

> GNU bash, version 4.3.48(1)-release (x86_64-pc-linux-gnu) ble.sh, version 0.4.0-devel3+b9fdaab (noarch) oh-my-bash (powerline), version 1.0.0+209ffda0 (noarch), aliases(general), completions(git composer ssh), plugins(git bashmarks) locale: LANG=en_US.UTF-8 LC_ADDRESS=zh_CN.UTF-8 LC_COLLATE=C LC_CTYPE=en_US.UTF-8 LC_IDENTIFICATION=zh_CN.UTF-8 LC_MEASUREMENT=zh_CN.UTF-8 LC_MONETARY=zh_CN.UTF-8 LC_NAME=zh_CN.UTF-8 LC_NUMERIC=zh_CN.UTF-8 LC_PAPER=zh_CN.UTF-8 LC_TELEPHONE=zh_CN.UTF-8 LC_TIME=zh_CN.UTF-8 terminal: TERM=xterm wcwidth=8.0-west/14.0-2+ri, vte:2802 (1;2802;0)

Thank you for the information! I'll later check it in detail.

**Comment by dongxi8** [comment]
> Hmm, OK!
> 
> > GNU bash, version 4.3.48(1)-release (x86_64-pc-linux-gnu) ble.sh, version 0.4.0-devel3+b9fdaab (noarch) oh-my-bash (powerline), version 1.0.0+209ffda0 (noarch), aliases(general), completions(git composer ssh), plugins(git bashmarks) locale: LANG=en_US.UTF-8 LC_ADDRESS=zh_CN.UTF-8 LC_COLLATE=C LC_CTYPE=en_US.UTF-8 LC_IDENTIFICATION=zh_CN.UTF-8 LC_MEASUREMENT=zh_CN.UTF-8 LC_MONETARY=zh_CN.UTF-8 LC_NAME=zh_CN.UTF-8 LC_NUMERIC=zh_CN.UTF-8 LC_PAPER=zh_CN.UTF-8 LC_TELEPHONE=zh_CN.UTF-8 LC_TIME=zh_CN.UTF-8 terminal: TERM=xterm wcwidth=8.0-west/14.0-2+ri, vte:2802 (1;2802;0)
> 
> Thank you for the information! I'll later check it in detail.

hope for your response

**Comment by dongxi8** [comment]
have any update?

**Comment by akinomyoga** [comment]
I'm busy so cannot take full time on working it, so it may take some time. At least, I cannot reproduce the problem with Terminator 1.91 in Ubuntu 20.04 LTS. I'm now preparing to set up a new virtual machine and install Ubuntu 16.04 LTS in it.

**Comment by akinomyoga** [comment]
I could reproduce the problem in Terminator 0.98 in Ubuntu 16.04 LTS. I'll later investigate what causes the problem. Thank you.

**Comment by akinomyoga** [comment]
This is a bug of the old library `vte-0.28.2` that Terminator 0.98 is relying on. Terminator 0.98 (or `vte-0.28.2`) doesn't support the terminal control function `DECSCUSR` yet sets `TERM=xterm` environment variable. `TERM=xterm` implies that the terminal supports `DECSCUSR` although Terminator 0.98 doesn't actually support it. You can check the problematic behavior of Terminator by running the following command (without ble.sh) where you'll see some garbage strings in Terminator 0.98:

```bash
$ tput Ss 1
$
``` 

I pushed a workaround https://github.com/akinomyoga/ble.sh/commit/70277d0758d1b649543abe3cf1cf89bd1fa22b1b in ble.sh `master` branch. You can update ble-0.4 by running `ble-update`. In the workaround, ble.sh doesn't use `DECSCUSR` when it detects an old version of `vte` library even if the `TERM` environment variable says `DECSCUSR` is available.

**Comment by dongxi8** [comment]
> This is a bug of the old library `vte-0.28.2` that Terminator 0.98 is relying on. Terminator 0.98 (or `vte-0.28.2`) doesn't support the terminal control function `DECSCUSR` yet sets `TERM=xterm` environment variable. `TERM=xterm` implies that the terminal supports `DECSCUSR` although Terminator 0.98 doesn't actually support it. You can check the problematic behavior of Terminator by running the following command (without ble.sh) where you'll see some garbage strings in Terminator 0.98:
> 
> ```shell
> $ tput Ss 1
> $
> ```
> 
> I pushed a workaround [akinomyoga/ble.sh@70277d0](https://github.com/akinomyoga/ble.sh/commit/70277d0758d1b649543abe3cf1cf89bd1fa22b1b) in ble.sh `master` branch. You can update ble-0.4 by running `ble-update`. In the workaround, ble.sh doesn't use `DECSCUSR` when it detects an old version of `vte` library even if the `TERM` environment variable says `DECSCUSR` is available.

thanks so much.

It works well

**Comment by akinomyoga** [comment]
OK! Thank you for checking! I close the issue.
